workflows:
  default-workflow:
    name: Build Flutter APK
    environment:
      flutter: stable
    scripts:
      - flutter --version
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
