workflows:
  debug-workflow:
    name: Debug Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ENV: debug
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK (Debug)
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    cache:
      paths:
        - ~/.pub-cache
